---
subtitle: "EUROPEAN CAUSAL INFERENCE MEETING</br> Program"
toc: true
toc-depth: 2
---

::: {.callout-tip}
## Important information

If you are presenting a poster, please review the information [at this link](poster-information.qmd).

:::


# Time schedule

Click on speaker/session titles to view abstracts, [view the list of talk abstracts](talk-abstracts.qmd), or [view the list of poster abstracts](poster-abstracts.qmd).

## Locations

Keynotes and tandem sessions will be in **Room L1**. 

The parallel sessions in the right column will be in **Room L2**.

::: {.panel-tabset}

## Wednesday (15th April)

<div class="table-card">
<table class="dataframe eurocim-table">
<tbody>
<tr>
<td>09:00-10:00</td>
<td colspan="2">__Keynote:__ [__Thomas Richardson__](talk-abstracts.html#thomas-richardson)</td>
</tr>
<tr>
<td>10:00-10.20</td>
<td colspan="2">Coffee Break</td>
</tr>
<tr>
<td>10:20-11:20</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Difference in Differences__](talk-abstracts.html#difference-in-differences) <br/> Yuhang Zhang<br/> Juejue Wang<br/> Michel Haddad</td>
<td>[__Causal Discovery__](talk-abstracts.html#causal-discovery)<br/> Enrico Roma<br/> Alex Markham<br/> Christine Bang</td>
</tr>
<tr>
<td>11:20-12:20</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Complex Applications__](talk-abstracts.html#complex-applications)<br/> Suehyun Kim <br/> Nia Kang<br/>  Michael Wallace</td>
<td>[__Graphical__](talk-abstracts.html#graphical)<br/> Rohit Bhattacharya<br/> Tess Baker<br/> Catharina Stoltenberg</td>
</tr>
<tr>
<td>12:20-13:50</td>
<td colspan="2">Lunch and [Poster Session](poster-abstracts.html)</td>
</tr>
<tr>
<td>13:50-15:10</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Instrumental Variables__](talk-abstracts.html#instrumental-variables)<br/> Mei Dong<br/> Jin Hong Du <br/> Anastasiia Holovchak <br/> Luke Keele</td>
<td>[__Complex Outcomes and Estimands__](talk-abstracts.html#complex-outcomes-and-estimands)<br/> Linbo Wang<br/> Mats Julius Stensrud  <br/> Salvador Balkus <br/> Laura Fuentes-Vicente </td>
</tr>
<tr>
<td>15:10-15:30</td>
<td colspan="2">Coffee Break</td>
</tr>
<tr>
<td>15:30-17:00</td>
<td colspan="2">__Tandem Session:__<br/> [Pål Ryalen](talk-abstracts.html#pal-ryalen) &amp; [Helene Rytgaard](talk-abstracts.html#helene-rytgaard)</td>
</tr>
<tr>
<td>17:00</td>
<td colspan="2">END</td>
</tr>
</tbody>
</table>
</div>

## Thursday (16th April) 

<div class="table-card">
<table class="dataframe eurocim-table">
<tbody>
<tr>
<td>09:00-10:00</td>
<td colspan="2">__Keynote:__ [Negar Kiyavash](talk-abstracts.html#negar-kiyavash)</td>
</tr>
<tr>
<td>10:00-11:00</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Mediation__](talk-abstracts.html#mediation) <br/> Marie-Felicia Beclin <br/> Lukas Laffers<br/>Felix Elwert</td>
<td>[__Sensitivity and Bounds__](talk-abstracts.html#sensitivity-and-bounds)<br/>Martina Scauda<br/>Sina Akbari<br/>Gellért Perényi</td>
</tr>
<tr>
<td>11:00-11:20</td>
<td colspan="2">Coffee Break</td>
</tr>
<tr>
<td>11:20-12:40</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Practical Data Challenges__](talk-abstracts.html#practical-data-challenges)<br/>Theresa M. A. Schmitz<br/>Leah Pirondini<br/>Silvan Vollmer<br/>Ruth Keogh
 </td>
<td>[__Heterogeneous Effects__](talk-abstracts.html#heterogeneous-effects)<br/>Anders Munch<br/>Michael Cork<br/>Simon Christoffer Ziersen<br/>Johanna Kutz</td>
</tr>
<tr>
<td>12:40-14:10</td>
<td colspan="2">Lunch and [Poster Session](poster-abstracts.html)</td>
</tr>
<tr>
<td>14:10-15:10</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Complex Treatment/Exposures__](talk-abstracts.html#complex-treatmentexposures)<br/>Nicholas Williams<br/>Laura Forastiere<br/>Federico Bertoia</td>
<td>[__Emulated Trials__](talk-abstracts.html#emulated-trials)<br/>Emily Wu<br/>Shunzhuang Huang<br/>Edoardo Efrem Gervasoni</td>
</tr>
<tr>
<td>15:10-15:30</td>
<td colspan="2">Coffee Break</td>
</tr>
<tr>
<td>15:30-17:00</td>
<td colspan="2">__Tandem Session:__<br/>[__Elizabeth Williamson &amp; Johan Manuel de Aguas Pérez__](talk-abstracts.html#fizzjohan)</td>
</tr>
<tr>
<td>17:00</td>
<td colspan="2">END</td>
</tr>
</tbody>
</table>
</div>

## Friday (17th April) {.active}


<div class="table-card">
<table class="dataframe eurocim-table">
<tbody>
<tr>
<td>09:00-10:30</td>
<td colspan="2">__Tandem Session:__<br/>[Corwin M Zigler](talk-abstracts.html#corwin-m-zigler)  &amp; [Fredrik Sävje](talk-abstracts.html#fredrik-sävje) </td>
</tr>
<tr>
<td>10:30-10:50</td>
<td colspan="2">Coffee Break</td>
</tr>
<tr>
<td>10:50-11:50</td>
<td colspan="2"> __Parallel Sessions__</td>
</tr>
<tr>
<td></td>
<td> Room L1</td>
<td> Room L2</td>
</tr>
<tr>
<td></td>
<td>[__Heterogeneous Effects Extensions__](talk-abstracts.html#heterogeneous-effects-extensions)<br/>Paweł Morzywołek<br/>Philipp Bach<br/>Angelos Alexopoulos </td>
<td>[__Transportability__](talk-abstracts.html#transportability)<br/>Veronica Ballerini<br/>Tat-Thang Vo<br/>Rhian Daniel</td>
</tr>
<tr>
<td>11:50-12:30</td>
<td colspan="2">Lunch</td>
</tr>
<tr>
<td>12:30-13:30</td>
<td colspan="2">__Keynote:__ [Philip Dawid](talk-abstracts.html#philip-dawid)</td>
</tr>
<tr>
<td>13:30-14:30</td>
<td colspan="2">__Panel:__ Philosophical Perspectives on Causal Inference, and How to Translate Those into Practice<br/>__Panelists:__ Nancy Cartwright, Philip Dawid, Sander Beckers</td>
</tr>
<tr>
<td>14:30</td>
<td colspan="2">END</td>
</tr>
</tbody>
</table>
</div>

:::
